const list = [
  { rank: 1, name: 'Mandarin Chinese', iso: 'cmn', speakers: 939000000, family: 'Sino-Tibetan', branch: 'Sinitic' },
  { rank: 2, name: 'Spanish', iso: 'spa', speakers: 485000000, family: 'Indo-European', branch: 'Romance' },
  { rank: 3, name: 'English', iso: 'eng', speakers: 380000000, family: 'Indo-European', branch: 'Germanic' },
  { rank: 4, name: 'Hindi', iso: 'hin', speakers: 345000000, family: 'Indo-European', branch: 'Indo-Aryan' },
  { rank: 5, name: 'Portuguese', iso: 'por', speakers: 236000000, family: 'Indo-European', branch: 'Romance' },
  { rank: 6, name: 'Bengali', iso: 'ben', speakers: 234000000, family: 'Indo-European', branch: 'Indo-Aryan' },
  { rank: 7, name: 'Russian', iso: 'rus', speakers: 148000000, family: 'Indo-European', branch: 'Balto-Slavic' },
  { rank: 8, name: 'Japanese', iso: 'jpn', speakers: 123000000, family: 'Japonic', branch: '' },
  { rank: 9, name: 'Western Punjabi', iso: 'pnb', speakers: 92700000, family: 'Indo-European', branch: 'Indo-Aryan' },
  { rank: 10, name: 'Yue Chinese', iso: 'yue', speakers: 85600000, family: 'Sino-Tibetan', branch: 'Sinitic' },
  { rank: 11, name: 'Vietnamese', iso: 'vie', speakers: 85300000, family: 'Austroasiatic', branch: 'Vietic' },
  { rank: 12, name: 'Turkish', iso: 'tur', speakers: 84000000, family: 'Turkic', branch: 'Oghuz' },
  { rank: 13, name: 'Marathi', iso: 'mar', speakers: 83100000, family: 'Indo-European', branch: 'Indo-Aryan' },
  { rank: 14, name: 'Telugu', iso: 'tel', speakers: 83000000, family: 'Dravidian', branch: 'South-Central' },
  { rank: 15, name: 'Korean', iso: 'kor', speakers: 81700000, family: 'Koreanic', branch: '' },
  { rank: 16, name: 'Wu Chinese', iso: 'wuu', speakers: 81400000, family: 'Sino-Tibetan', branch: 'Sinitic' },
  { rank: 17, name: 'French', iso: 'fra', speakers: 80000000, family: 'Indo-European', branch: 'Romance' },
  { rank: 18, name: 'Tamil', iso: 'tam', speakers: 78600000, family: 'Dravidian', branch: 'South' },
  { rank: 19, name: 'Egyptian Arabic', iso: 'arz', speakers: 77400000, family: 'Afro-Asiatic', branch: 'Semitic' },
  { rank: 20, name: 'Standard German', iso: 'deu', speakers: 76100000, family: 'Indo-European', branch: 'Germanic' },
  { rank: 21, name: 'Urdu', iso: 'urd', speakers: 70200000, family: 'Indo-European', branch: 'Indo-Aryan' },
  { rank: 22, name: 'Javanese', iso: 'jav', speakers: 68300000, family: 'Austronesian', branch: 'Malayo-Polynesian' },
  { rank: 23, name: 'Western Persian', iso: 'pes', speakers: 65000000, family: 'Indo-European', branch: 'Iranian' },
  { rank: 24, name: 'Italian', iso: 'ita', speakers: 63400000, family: 'Indo-European', branch: 'Romance' },
  { rank: 25, name: 'Gujarati', iso: 'guj', speakers: 57100000, family: 'Indo-European', branch: 'Indo-Aryan' },
  { rank: 26, name: 'Hausa', iso: 'hau', speakers: 53400000, family: 'Afro-Asiatic', branch: 'Chadic' },
  { rank: 27, name: 'Bhojpuri', iso: 'bho', speakers: 52300000, family: 'Indo-European', branch: 'Indo-Aryan' },
  { rank: 28, name: 'Eastern Punjabi', iso: 'pan', speakers: 51700000, family: 'Indo-European', branch: 'Indo-Aryan' },
  { rank: 29, name: 'Min Nan Chinese', iso: 'nan', speakers: 49300000, family: 'Sino-Tibetan', branch: 'Sinitic' },
  { rank: 30, name: 'Thai', iso: 'tha', speakers: 47000000, family: 'Kra-Dai', branch: 'Tai' },
  { rank: 31, name: 'Tagalog', iso: 'tgl', speakers: 45000000, family: 'Austronesian', branch: 'Malayo-Polynesian' },
  { rank: 32, name: 'Northern Pashto', iso: 'pbu', speakers: 45000000, family: 'Indo-European', branch: 'Iranian' },
  { rank: 33, name: 'Polish', iso: 'pol', speakers: 45000000, family: 'Indo-European', branch: 'Balto-Slavic' },
  { rank: 34, name: 'Kannada', iso: 'kan', speakers: 44000000, family: 'Dravidian', branch: 'South' },
  { rank: 35, name: 'Indonesian', iso: 'ind', speakers: 43600000, family: 'Austronesian', branch: 'Malayo-Polynesian' },
  { rank: 36, name: 'Yoruba', iso: 'yor', speakers: 43000000, family: 'Niger-Congo', branch: 'Atlantic-Congo' },
  { rank: 37, name: 'Xiang Chinese', iso: 'hsn', speakers: 38000000, family: 'Sino-Tibetan', branch: 'Sinitic' },
  { rank: 38, name: 'West Central Oromo', iso: 'gaz', speakers: 37500000, family: 'Afro-Asiatic', branch: 'Cushitic' },
  { rank: 39, name: 'Malayalam', iso: 'mal', speakers: 37200000, family: 'Dravidian', branch: 'South' },
  { rank: 40, name: 'Odia', iso: 'ory', speakers: 37000000, family: 'Indo-European', branch: 'Indo-Aryan' },
  { rank: 41, name: 'Maithili', iso: 'mai', speakers: 34400000, family: 'Indo-European', branch: 'Indo-Aryan' },
  { rank: 42, name: 'Ukrainian', iso: 'ukr', speakers: 33800000, family: 'Indo-European', branch: 'Balto-Slavic' },
  { rank: 43, name: 'Burmese', iso: 'mya', speakers: 33000000, family: 'Sino-Tibetan', branch: 'Tibeto-Burman' },
  { rank: 44, name: 'Sundanese', iso: 'sun', speakers: 32400000, family: 'Austronesian', branch: 'Malayo-Polynesian' },
  { rank: 45, name: 'Algerian Arabic', iso: 'arq', speakers: 29400000, family: 'Afro-Asiatic', branch: 'Semitic' },
  { rank: 46, name: 'Cebuano', iso: 'ceb', speakers: 27300000, family: 'Austronesian', branch: 'Malayo-Polynesian' },
  { rank: 47, name: 'Igbo', iso: 'ibo', speakers: 27000000, family: 'Niger-Congo', branch: 'Atlantic-Congo' },
  { rank: 48, name: 'Uzbek', iso: 'uzb', speakers: 27000000, family: 'Turkic', branch: 'Karluk' },
  { rank: 49, name: 'Sindhi', iso: 'snd', speakers: 26000000, family: 'Indo-European', branch: 'Indo-Aryan' },
  { rank: 50, name: 'Dutch', iso: 'nld', speakers: 25000000, family: 'Indo-European', branch: 'Germanic' },
  { rank: 51, name: 'Azerbaijani', iso: 'aze', speakers: 24300000, family: 'Turkic', branch: 'Oghuz' },
  { rank: 52, name: 'Romanian', iso: 'ron', speakers: 23800000, family: 'Indo-European', branch: 'Romance' },
  { rank: 53, name: 'Amharic', iso: 'amh', speakers: 21800000, family: 'Afro-Asiatic', branch: 'Semitic' },
  { rank: 54, name: 'Somali', iso: 'som', speakers: 21800000, family: 'Afro-Asiatic', branch: 'Cushitic' },
  { rank: 55, name: 'Sinhala', iso: 'sin', speakers: 19000000, family: 'Indo-European', branch: 'Indo-Aryan' },
  { rank: 56, name: 'Malagasy', iso: 'plt', speakers: 18700000, family: 'Austronesian', branch: 'Malayo-Polynesian' },
  { rank: 57, name: 'Nepali', iso: 'npi', speakers: 17000000, family: 'Indo-European', branch: 'Indo-Aryan' },
  { rank: 58, name: 'Khmer', iso: 'khm', speakers: 16000000, family: 'Austroasiatic', branch: 'Khmeric' },
  { rank: 59, name: 'Assamese', iso: 'asm', speakers: 15300000, family: 'Indo-European', branch: 'Indo-Aryan' },
  { rank: 60, name: 'Shona', iso: 'sna', speakers: 14800000, family: 'Niger-Congo', branch: 'Bantu' },
  { rank: 61, name: 'Kinyarwanda', iso: 'kin', speakers: 14000000, family: 'Niger-Congo', branch: 'Bantu' },
  { rank: 62, name: 'Kazakh', iso: 'kaz', speakers: 13400000, family: 'Turkic', branch: 'Kipchak' },
  { rank: 63, name: 'Hungarian', iso: 'hun', speakers: 12600000, family: 'Uralic', branch: 'Ugric' },
  { rank: 64, name: 'Zulu', iso: 'zul', speakers: 12100000, family: 'Niger-Congo', branch: 'Bantu' },
  { rank: 65, name: 'Haitian Creole', iso: 'hat', speakers: 12000000, family: 'Creole', branch: 'French-based' },
  { rank: 66, name: 'Greek', iso: 'ell', speakers: 11300000, family: 'Indo-European', branch: 'Hellenic' },
  { rank: 67, name: 'Uyghur', iso: 'uig', speakers: 11000000, family: 'Turkic', branch: 'Karluk' },
  { rank: 68, name: 'Czech', iso: 'ces', speakers: 10700000, family: 'Indo-European', branch: 'Balto-Slavic' },
  { rank: 69, name: 'Swedish', iso: 'swe', speakers: 10200000, family: 'Indo-European', branch: 'Germanic' },
  { rank: 70, name: 'Serbian', iso: 'srp', speakers: 10000000, family: 'Indo-European', branch: 'Balto-Slavic' },
  { rank: 71, name: 'Tigrinya', iso: 'tir', speakers: 9900000, family: 'Afro-Asiatic', branch: 'Semitic' },
  { rank: 72, name: 'Hebrew', iso: 'heb', speakers: 9400000, family: 'Afro-Asiatic', branch: 'Semitic' },
  { rank: 73, name: 'Tajik', iso: 'tgk', speakers: 8500000, family: 'Indo-European', branch: 'Iranian' },
  { rank: 74, name: 'Xhosa', iso: 'xho', speakers: 8200000, family: 'Niger-Congo', branch: 'Bantu' },
  { rank: 75, name: 'Bambara', iso: 'bam', speakers: 8000000, family: 'Niger-Congo', branch: 'Mande' },
  { rank: 76, name: 'Albanian', iso: 'sqi', speakers: 7500000, family: 'Indo-European', branch: 'Albanian' },
  { rank: 77, name: 'Bulgarian', iso: 'bul', speakers: 7500000, family: 'Indo-European', branch: 'Balto-Slavic' },
  { rank: 78, name: 'Afrikaans', iso: 'afr', speakers: 7100000, family: 'Indo-European', branch: 'Germanic' },
  { rank: 79, name: 'Croatian', iso: 'hrv', speakers: 7000000, family: 'Indo-European', branch: 'Balto-Slavic' },
  { rank: 80, name: 'Armenian', iso: 'hye', speakers: 6700000, family: 'Indo-European', branch: 'Armenian' },
  { rank: 81, name: 'Belarusian', iso: 'bel', speakers: 6700000, family: 'Indo-European', branch: 'Balto-Slavic' },
  { rank: 82, name: 'Turkmen', iso: 'tuk', speakers: 6700000, family: 'Turkic', branch: 'Oghuz' },
  { rank: 83, name: 'Lingala', iso: 'lin', speakers: 6600000, family: 'Niger-Congo', branch: 'Bantu' },
  { rank: 84, name: 'Tswana', iso: 'tsn', speakers: 5800000, family: 'Niger-Congo', branch: 'Bantu' },
  { rank: 85, name: 'Wolof', iso: 'wol', speakers: 5700000, family: 'Niger-Congo', branch: 'Atlantic' },
  { rank: 86, name: 'Halh Mongolian', iso: 'khk', speakers: 5700000, family: 'Mongolic', branch: 'Central' },
  { rank: 87, name: 'Slovak', iso: 'slk', speakers: 5600000, family: 'Indo-European', branch: 'Balto-Slavic' },
  { rank: 88, name: 'Danish', iso: 'dan', speakers: 5500000, family: 'Indo-European', branch: 'Germanic' },
  { rank: 89, name: 'Finnish', iso: 'fin', speakers: 4900000, family: 'Uralic', branch: 'Finnic' },
  { rank: 90, name: 'Norwegian Bokmål', iso: 'nob', speakers: 4600000, family: 'Indo-European', branch: 'Germanic' },
  { rank: 91, name: 'Kyrgyz', iso: 'kir', speakers: 4500000, family: 'Turkic', branch: 'Kipchak' },
  { rank: 92, name: 'Catalan', iso: 'cat', speakers: 4100000, family: 'Indo-European', branch: 'Romance' },
  { rank: 93, name: 'Lao', iso: 'lao', speakers: 4300000, family: 'Kra-Dai', branch: 'Tai' },
  { rank: 94, name: 'Kongo', iso: 'kon', speakers: 4300000, family: 'Niger-Congo', branch: 'Bantu' },
  { rank: 95, name: 'Southern Sotho', iso: 'sot', speakers: 4100000, family: 'Niger-Congo', branch: 'Bantu' },
  { rank: 96, name: 'Fula', iso: 'fuf', speakers: 4000000, family: 'Niger-Congo', branch: 'Atlantic' },
  { rank: 97, name: 'Georgian', iso: 'kat', speakers: 3600000, family: 'Kartvelian', branch: '' },
  { rank: 98, name: 'Balochi', iso: 'bal', speakers: 3500000, family: 'Indo-European', branch: 'Iranian' },
  { rank: 99, name: 'Swati', iso: 'ssw', speakers: 3100000, family: 'Niger-Congo', branch: 'Bantu' },
  { rank: 100, name: 'Lithuanian', iso: 'lit', speakers: 3000000, family: 'Indo-European', branch: 'Baltic' },
  { rank: 101, name: 'Chichewa', iso: 'nya', speakers: 2900000, family: 'Niger-Congo', branch: 'Bantu' },
  { rank: 102, name: 'Northern Sotho', iso: 'nso', speakers: 4600000, family: 'Niger-Congo', branch: 'Bantu' },
  { rank: 103, name: 'Tsonga', iso: 'tso', speakers: 2600000, family: 'Niger-Congo', branch: 'Bantu' },
  { rank: 104, name: 'Sinhalese (dialect)', iso: 'sin', speakers: 2500000, family: 'Indo-European', branch: 'Indo-Aryan' },
  { rank: 105, name: 'Kurdish (Sorani)', iso: 'ckb', speakers: 8000000, family: 'Indo-European', branch: 'Iranian' },
  { rank: 106, name: 'Kurmanji Kurdish', iso: 'kmr', speakers: 9000000, family: 'Indo-European', branch: 'Iranian' },
  { rank: 107, name: 'Oriya / Odia', iso: 'ori', speakers: 37000000, family: 'Indo-European', branch: 'Indo-Aryan' },
  { rank: 108, name: 'Minangkabau', iso: 'min', speakers: 5500000, family: 'Austronesian', branch: 'Malayo-Polynesian' },
  { rank: 109, name: 'Latvian', iso: 'lav', speakers: 1600000, family: 'Indo-European', branch: 'Baltic' },
  { rank: 110, name: 'Macedonian', iso: 'mkd', speakers: 2000000, family: 'Indo-European', branch: 'Balto-Slavic' },
  { rank: 111, name: 'Madurese', iso: 'mad', speakers: 7000000, family: 'Austronesian', branch: 'Malayo-Polynesian' },
  { rank: 112, name: 'Lombard', iso: 'lmo', speakers: 3500000, family: 'Indo-European', branch: 'Romance' },
  { rank: 113, name: 'Fante', iso: 'fat', speakers: 1900000, family: 'Niger-Congo', branch: 'Kwa' },
  { rank: 114, name: 'South Azerbaijani', iso: 'azb', speakers: 13000000, family: 'Turkic', branch: 'Oghuz' },
  { rank: 115, name: 'Harari', iso: 'har', speakers: 56000, family: 'Afro-Asiatic', branch: 'Semitic' },
  { rank: 116, name: 'Batak Toba', iso: 'bbc', speakers: 2000000, family: 'Austronesian', branch: 'Malayo-Polynesian' },
  { rank: 117, name: 'Nepali (India)', iso: 'npi', speakers: 2900000, family: 'Indo-European', branch: 'Indo-Aryan' },
  { rank: 118, name: 'Tok Pisin', iso: 'tpi', speakers: 2000000, family: 'Creole', branch: 'English-based' },
  { rank: 119, name: 'Hiligaynon', iso: 'hil', speakers: 9300000, family: 'Austronesian', branch: 'Malayo-Polynesian' },
  { rank: 120, name: 'Gan Chinese', iso: 'gan', speakers: 22000000, family: 'Sino-Tibetan', branch: 'Sinitic' },
  { rank: 121, name: 'Hakka Chinese', iso: 'hak', speakers: 43500000, family: 'Sino-Tibetan', branch: 'Sinitic' },
  { rank: 122, name: 'Tibetan', iso: 'bod', speakers: 6200000, family: 'Sino-Tibetan', branch: 'Tibeto-Burman' },
  { rank: 123, name: 'Konkani', iso: 'kok', speakers: 2400000, family: 'Indo-European', branch: 'Indo-Aryan' },
  { rank: 124, name: 'Santali', iso: 'sat', speakers: 7600000, family: 'Austroasiatic', branch: 'Munda' },
  { rank: 125, name: 'Rajasthani', iso: 'raj', speakers: 80000000, family: 'Indo-European', branch: 'Indo-Aryan' },
  { rank: 126, name: 'Dogri', iso: 'doi', speakers: 2600000, family: 'Indo-European', branch: 'Indo-Aryan' },
  { rank: 127, name: 'Manipuri', iso: 'mni', speakers: 1760000, family: 'Sino-Tibetan', branch: 'Tibeto-Burman' },
  { rank: 128, name: 'Kashmiri', iso: 'kas', speakers: 7100000, family: 'Indo-European', branch: 'Indo-Aryan' },
  { rank: 129, name: 'Shan', iso: 'shn', speakers: 3300000, family: 'Kra-Dai', branch: 'Tai' },
  { rank: 130, name: 'Zhuang', iso: 'zha', speakers: 16900000, family: 'Kra-Dai', branch: 'Tai' },
  { rank: 131, name: 'Tujia', iso: 'tjs', speakers: 8000000, family: 'Sino-Tibetan', branch: 'Tibeto-Burman' },
  { rank: 132, name: 'Yi', iso: 'iii', speakers: 2100000, family: 'Sino-Tibetan', branch: 'Tibeto-Burman' },
  { rank: 133, name: 'Miao/Hmong', iso: 'hmn', speakers: 9000000, family: 'Hmong-Mien', branch: '' },
  { rank: 134, name: 'Uighur', iso: 'uig', speakers: 11000000, family: 'Turkic', branch: 'Karluk' },
  { rank: 135, name: 'Estonian', iso: 'est', speakers: 1100000, family: 'Uralic', branch: 'Finnic' },
  { rank: 136, name: 'Slovene', iso: 'slv', speakers: 2100000, family: 'Indo-European', branch: 'Balto-Slavic' },
  { rank: 137, name: 'Bosnian', iso: 'bos', speakers: 2700000, family: 'Indo-European', branch: 'Balto-Slavic' },
  { rank: 138, name: 'Welsh', iso: 'cym', speakers: 580000, family: 'Indo-European', branch: 'Celtic' },
  { rank: 139, name: 'Galician', iso: 'glg', speakers: 2400000, family: 'Indo-European', branch: 'Romance' },
  { rank: 140, name: 'Basque', iso: 'eus', speakers: 750000, family: 'Language isolate', branch: '' },
  { rank: 141, name: 'Irish', iso: 'gle', speakers: 170000, family: 'Indo-European', branch: 'Celtic' },
  { rank: 142, name: 'Maltese', iso: 'mlt', speakers: 520000, family: 'Afro-Asiatic', branch: 'Semitic' },
  { rank: 143, name: 'Icelandic', iso: 'isl', speakers: 314000, family: 'Indo-European', branch: 'Germanic' },
  { rank: 144, name: 'Faroese', iso: 'fao', speakers: 72000, family: 'Indo-European', branch: 'Germanic' },
  { rank: 145, name: 'Luxembourgish', iso: 'ltz', speakers: 400000, family: 'Indo-European', branch: 'Germanic' },
  { rank: 146, name: 'Sorbian (Upper)', iso: 'hsb', speakers: 13000, family: 'Indo-European', branch: 'Balto-Slavic' },
  { rank: 147, name: 'Quechua', iso: 'que', speakers: 10000000, family: 'Quechuan', branch: '' },
  { rank: 148, name: 'Guaraní', iso: 'gug', speakers: 6500000, family: 'Tupian', branch: '' },
  { rank: 149, name: 'Nahuatl', iso: 'nah', speakers: 1700000, family: 'Uto-Aztecan', branch: '' },
  { rank: 150, name: 'Swahili', iso: 'swh', speakers: 16000000, family: 'Niger-Congo', branch: 'Bantu' },
  { name: 'Noakhailla', iso: 'oak', speakers: 15000000, family: 'Indo-European', branch: 'Indo-Aryan' },
  { name: 'Sylheti', iso: 'syl', speakers: 14500000, family: 'Indo-European', branch: 'Indo-Aryan' },
  { name: 'Chittagonian', iso: 'ctg', speakers: 13500000, family: 'Indo-European', branch: 'Indo-Aryan' }
];

list.sort((a, b) => b.speakers - a.speakers);

const result = list.slice(0, 150).map((l, i) => {
    return { rank: i + 1, ...l };
});

console.log('const ETHNOLOGUE_TOP150 = ' + JSON.stringify(result, null, 2) + ';');
